networks:
  default:
    name: micrsservice-net

services:
  rmqnamesrv:
    image: apache/rocketmq:4.9.7
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmqnamesrv/logs:/home/rocketmq/logs
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"  
    command: sh mqnamesrv

  rmqbroker:
    image: apache/rocketmq:4.9.7
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./rmqbroker/logs:/home/rocketmq/logs
      - ./rmqbroker/store:/home/rocketmq/store
      - ./rmqbroker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.7/conf/broker.conf
    links:
      - rmqnamesrv:namesrv
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: sh mqbroker -c ../conf/broker.conf

  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - 8080:8080
    volumes:
      - ./rmqdashboard/data:/tmp/rocketmq-console/data  
    environment:
      NAMESRV_ADDR: namesrv:9876
      ROCKETMQ_CONFIG_LOGIN_REQUIRED: "true"
    links:
      - rmqnamesrv:namesrv

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/schema/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    env_file:
      - ./nacos/conf/nacos-standlone-mysql.env
    volumes:  
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - 8848:8848
      - 9848:9848
    privileged: true
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: unless-stopped
    command: '--requirepass $REDIS_PASSWORD'
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379